apiVersion: apps/v1
kind: Deployment
metadata:
  name: nikapp01
spec:
  selector:
    matchLabels:
      app: nikapp01
  template:
    metadata:
      labels:
        app: nikapp01
    spec:
      containers:
      - name: nikapp01
        image: psacr02.azurecr.io/nikapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5178
